# Generated by Django 3.2.7 on 2021-10-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_product_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su_name', models.CharField(max_length=200, null=True)),
                ('su_group', models.CharField(choices=[('1', 'Cashier'), ('2', 'Account'), ('3', 'Whouse'), ('4', 'Manager'), ('5', 'Sales'), ('6', 'Admin'), ('7', 'Guest')], max_length=1, null=True)),
                ('su_level', models.CharField(choices=[('1', 'Level1'), ('2', 'Level2'), ('3', 'Level3')], max_length=1, null=True)),
                ('su_br', models.CharField(choices=[('0', 'HO'), ('1', 'DR'), ('2', 'RR'), ('3', 'JR'), ('4', 'KR'), ('5', 'S1'), ('6', 'MW')], max_length=1, null=True)),
                ('su_pricing', models.CharField(choices=[('0', 'Any'), ('1', 'Retail'), ('2', 'Dealer')], max_length=1, null=True)),
            ],
        ),
    ]
