# Generated by Django 3.2.7 on 2021-10-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_salesuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesuser',
            name='su_br',
            field=models.CharField(choices=[('HO', 'HO'), ('DR', 'DR'), ('RR', 'RR'), ('JR', 'JR'), ('KR', 'KR'), ('S!', 'S1'), ('MW', 'MW')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='su_group',
            field=models.CharField(choices=[('CA', 'Cashier'), ('AC', 'Account'), ('WH', 'Whouse'), ('MA', 'Manager'), ('SA', 'Sales'), ('AD', 'Admin'), ('GU', 'Guest')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='su_level',
            field=models.CharField(choices=[('L1', 'Level1'), ('L2', 'Level2'), ('L3', 'Level3')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='su_pricing',
            field=models.CharField(choices=[('Any', 'Any'), ('Retail', 'Retail'), ('Dealer', 'Dealer')], max_length=6, null=True),
        ),
    ]
