# Generated by Django 3.2.7 on 2021-10-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211005_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesuser',
            name='su_group',
            field=models.CharField(choices=[('CA', 'Cashier'), ('AC', 'Account'), ('WH', 'Whouse'), ('MA', 'Manager'), ('SA', 'Sales'), ('AD', 'Admin'), ('GU', 'Guest'), ('CO', 'Control')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='salesuser',
            unique_together={('su_name',)},
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='StockClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='StockCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='StockBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_no', models.CharField(default='0', max_length=8, null=True)),
                ('stock_name', models.CharField(max_length=50, null=True)),
                ('stock_model', models.CharField(max_length=20, null=True)),
                ('stock_qin', models.FloatField(default=0, null=True)),
                ('stock_qout', models.FloatField(default=0, null=True)),
                ('stock_bf', models.FloatField(default=0, null=True)),
                ('stock_price', models.FloatField(default=0, null=True)),
                ('stock_ucost', models.FloatField(default=0, null=True)),
                ('stock_location', models.CharField(default='*', max_length=20, null=True)),
                ('stock_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.stockbrand')),
                ('stock_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.stockcat')),
                ('stock_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.stockclass')),
                ('stock_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.stockunit')),
            ],
            options={
                'unique_together': {('stock_no', 'stock_name')},
            },
        ),
    ]
