# Generated by Django 3.2.7 on 2021-10-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211007_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_cat',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name',)},
        ),
    ]
