# Generated by Django 3.2.7 on 2021-10-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211009_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesuser',
            name='su_br',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
