# Generated by Django 3.2.7 on 2021-10-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_salesuser_su_br'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_less',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_vat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='su_br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch'),
        ),
    ]
